/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef aafw_CONSTANTS_H
#define aafw_CONSTANTS_H

#include "aafw_types.h"

namespace aafw {

class aafwConstants {
 public:
  aafwConstants();

};

extern const aafwConstants g_aafw_constants;

} // namespace

#endif
